on:
  push:
    branches:
      - main
    paths: [ '**.html', '**.pdf','**.css' ]  

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1.10.0
      with:
        base-url-path: https://nhhsmun.org
      
    - name: Commit and Push Changes
      run: |
        git add ${{ steps.sitemap.outputs.sitemap-path }}
        git commit -m "Automated sitemap update."
        git push origin HEAD
