on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate Sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1.10.0
      with:
        base-url-path: https://nhhsmun.org
      
